window.REASONS = [
"The second I saw you, something in me stopped running.",
"The way your brown eyes hold warmth even when you’re quiet.",
"The golden highlights in your hair that catch light like secrets.",
"The way your long hair falls when you lean forward.",
"How you fix my hair without even realizing you’re doing it.",
"The softness you show only to me.",
"The chaos you unleash on everyone else.",
"How you overthink but still choose me every day.",
"The way you sleep on call with me like distance doesn’t matter.",
"How your silence feels safe, not empty.",
"The way you whisper ‘WA’ like it’s a secret language.",
"The way ‘WIWIIW’ somehow makes perfect sense coming from you.",
"How you call me ‘Tanish’ and it sounds different than anyone else saying it.",
"The comfort of you just existing beside me.",
"The way you pass out randomly when you’re sleepy.",
"How clingy you get and pretend you’re not.",
"Your jealous little moments that secretly make me feel wanted.",
"The way you scold me but still care too much.",
"How you cry softly instead of yelling.",
"The way you hug tighter when you’re sad.",
"How your full-time glasses make you look focused and adorable.",
"The smell of your shampoo lingering when you lean close.",
"How you spam call me just because you miss me.",
"The paragraphs you send when you really feel something.",
"The way you type fast when you’re excited.",
"The way you wait on calls even when you’re exhausted.",
"How you stayed awake all night just because I needed you.",
"The way you steal my hoodies and never return them.",
"How my clothes look better on you anyway.",
"The way you bite me when you’re being affectionate.",
"The way you hold my sleeve like I might disappear.",
"How you always come back to me even after overthinking everything.",
"The way you pretend you’re tough but melt instantly.",
"The way your nose scrunches when you laugh.",
"How your laugh sounds like relief.",
"The way you get super quiet when you’re jealous.",
"How you act mad but still text me two minutes later.",
"The way you say my name when you’re half asleep.",
"How dark rooms feel warmer when you’re there.",
"The way tulips remind me of you now.",
"How shawarma became special just because you love it.",
"The way you make ordinary food feel like a date.",
"The memory of sushi at Phoenix South with you.",
"The way that day felt like the start of my life changing.",
"How awkward and perfect our first date was.",
"The way you made waiting around shops feel fun.",
"The stupid massage chair moment that still makes me laugh.",
"How you looked surprised and embarrassed at the same time.",
"The way you trusted me enough to be silly.",
"How you’re chaotic in public but soft with me in private.",
"The way you pretend not to need me but always call.",
"How you overthink every small thing but never overthink loving me.",
"The way you send ‘where are you’ texts even when you know.",
"How you check if I’ve eaten.",
"The way you remember things I casually mention once.",
"How you worry about me more than yourself.",
"The way you get dramatic over tiny stuff.",
"How you calm down the second I say it’s okay.",
"The way you hide your face when you’re embarrassed.",
"How you get sleepy and start talking nonsense.",
"The way you sound cutest when half awake.",
"How you make late nights feel short.",
"The way you stay even when you’re tired.",
"How you choose calls over sleep.",
"The way you exist like home.",
"How you make me less hateful toward myself.",
"The way you healed parts of me you never even saw.",
"How loving you feels logical and emotional at the same time.",
"The way you make me want to be better.",
"How you don’t give up on me.",
"The way you quietly care without announcing it.",
"How you listen to every rant.",
"The way you send random ‘are you okay’ messages.",
"How you worry if I sound slightly off.",
"The way you make jealousy look cute instead of scary.",
"How you get possessive in the smallest ways.",
"The way you call me again if I don’t pick up.",
"How you spam texts until I respond.",
"The way you never let distance win.",
"How your presence feels heavier than the whole world.",
"The way you look through your glasses when you’re serious.",
"How you push your hair back when concentrating.",
"The way your highlights glow in sunlight.",
"How your eyes look darker at night.",
"The way you stare when you’re thinking.",
"How you pout when you don’t get your way.",
"The way you get fake angry just to tease me.",
"How you randomly send voice notes.",
"The way you say nonsense sounds and expect me to understand.",
"How we somehow always understand each other anyway.",
"The way you make even silence feel like a conversation.",
"How your hugs last longer than necessary.",
"The way you lean into me without noticing.",
"How you bite my arm like a tiny gremlin.",
"The way you cling when you don’t want me to leave.",
"How you always say you’re fine when you’re not.",
"The way you trust me enough to be vulnerable.",
"How you cry openly instead of pretending you’re strong.",
"The way you let me see your worst days.",
"How you still choose me on those days.",
"The way you turn simple moments into memories.",
"How loving you feels easy even when life isn’t.",
"The way every future I imagine automatically includes you.",
"The way you say my name when you’re annoyed but still soft.",
"How you pretend you’re not clingy while literally holding my sleeve.",
"The way you stay on call even after you fall asleep.",
"How your breathing slows and I just listen quietly.",
"The comfort of knowing you’re still there at 3am.",
"The way you randomly send ‘miss you’ texts out of nowhere.",
"How you get jealous over the smallest things and try to hide it.",
"The way you fail at hiding it every time.",
"How you pout like a kid when I tease you.",
"The way you get dramatic over tiny jokes.",
"How you say ‘WA’ like it’s a complete sentence.",
"The way I somehow understand exactly what it means.",
"How you create your own language and expect me to keep up.",
"The way I actually do keep up.",
"How you call me just to hear my voice.",
"The way you don’t hang up even after saying bye five times.",
"How you get quiet when you’re upset instead of yelling.",
"The way you cry softly and it breaks my heart.",
"How you let me comfort you even when you’re stubborn.",
"The way you trust me with your worst moods.",
"How you always come back after every overthinking spiral.",
"The way you ask if I’m mad even when I’m not.",
"How you worry about losing me while I’m scared of losing you.",
"The way you sit closer than necessary.",
"How you steal my hoodies and never feel guilty.",
"The way my hoodie smells like your shampoo afterward.",
"How you look tiny when you hide inside oversized sleeves.",
"The way you hold my arm like I’m your anchor.",
"How you bite me randomly like a gremlin.",
"The way you smile right after like nothing happened.",
"How you spam call until I pick up.",
"The way your notifications take over my phone.",
"How you send long paragraphs when you’re emotional.",
"The way you over-explain everything because you care too much.",
"How you say sorry even when it’s not your fault.",
"The way you try to fix things immediately.",
"How you check if I’ve eaten before asking about yourself.",
"The way you care in small invisible ways.",
"How you remember random details about me from months ago.",
"The way you bring up old conversations perfectly.",
"How you make me feel noticed.",
"The way you get sleepy and start talking nonsense.",
"How your voice gets softer and slower at night.",
"The way you mumble when you’re half asleep.",
"How you refuse to hang up first.",
"The way you say ‘stay’ without actually saying it.",
"How you make silence feel full instead of awkward.",
"The way you exist quietly beside me and that’s enough.",
"How you get embarrassed over compliments.",
"The way you look away when I stare too long.",
"How your glasses slide down your nose when you’re focused.",
"The way you push them back up absentmindedly.",
"How your hair falls over your face and you tuck it behind your ear.",
"The way the blonde highlights glow under light.",
"How your brown eyes look almost golden sometimes.",
"The way you squint when you laugh too hard.",
"How you cover your face when you’re shy.",
"The way you scrunch your nose when something’s funny.",
"How you look smaller when you’re sad.",
"The way you lean into me when you need comfort.",
"How you hug tighter when you don’t want me to leave.",
"The way you cling without realizing it.",
"How you say you’re fine but your voice gives you away.",
"The way you always tell me the truth eventually.",
"How you get protective over me.",
"The way you act tough but melt instantly.",
"How you pretend not to care but care the most.",
"The way you get jealous and then apologize.",
"How you look at me like I belong to you.",
"The way you make me feel chosen.",
"How you stayed awake all night once just because I needed you.",
"The way you sacrifice sleep for me.",
"How you pick calls over comfort.",
"The way you answer even when you’re exhausted.",
"How you make distance feel smaller.",
"The way hours pass fast when we talk.",
"How you make late nights feel peaceful.",
"The way you say ‘eepi sleepi’ and everything softens.",
"How that phrase feels like our little universe.",
"The way you laugh at dumb jokes I make.",
"How you encourage my weirdness instead of judging it.",
"The way you accept every strange part of me.",
"How you make me less harsh on myself.",
"The way you healed parts of me you never saw.",
"How you make me want to grow.",
"The way loving you feels natural, not forced.",
"How you feel like home instead of effort.",
"The way you make ordinary days special.",
"How shawarma tastes better because you love it.",
"The way tulips instantly remind me of you.",
"How dark rooms feel safe when I imagine you there.",
"The way you turn small moments into memories.",
"How even waiting around shops with you felt meaningful.",
"The way our first sushi date still plays in my head.",
"How awkward moments with you become my favorites.",
"The way you make me laugh when I least expect it.",
"How you’re both chaos and comfort at the same time.",
"The way you’re loud with the world but soft with me.",
"How you’re everything and still somehow just you.",
"The way every future I picture automatically has you in it.",
"The way you say my name when you’re half asleep and it sounds softer than anything.",
"How you pretend you’re not tired but fall asleep mid-sentence.",
"The way you breathe quietly on call and I just listen.",
"How you make even silence feel like company.",
"The way you ask what I’m doing every hour just to stay close.",
"How you send random updates about nothing important because you want to share everything with me.",
"The way you get fake mad and then smile two seconds later.",
"How you always end up forgiving me too quickly.",
"The way you hold grudges for exactly three minutes.",
"How you complain about me and then miss me immediately.",
"The way you say ‘fine’ when you’re clearly not fine.",
"How you expect me to magically understand you and somehow I do.",
"The way your voice changes when you’re jealous.",
"How you get extra clingy when you think I’m distant.",
"The way you pull me back without even realizing.",
"How you say ‘stay’ without using the word stay.",
"The way you always call again if I hang up too fast.",
"How you hate goodbyes and stretch them forever.",
"The way you wait for me even when I’m late.",
"How you never actually give up on me.",
"The way you talk softer when you’re being vulnerable.",
"How you look away when emotions get too real.",
"The way you trust me with your overthinking spirals.",
"How you let me see the messy parts of your mind.",
"The way you apologize too much for things that aren’t your fault.",
"How you care more about hurting me than being right.",
"The way you quietly check if I’m okay.",
"How you always ask if I’ve eaten or slept.",
"The way you scold me like you’re older than me.",
"How you act like my tiny angry grandma sometimes.",
"The way you get protective out of nowhere.",
"How you make me feel like I matter without saying it directly.",
"The way you randomly send ‘I miss you’ and ruin my focus.",
"How you always want one more minute on call.",
"The way time stretches when we’re together.",
"How hours feel like seconds with you.",
"The way you send heart emojis and then pretend you didn’t.",
"How you get shy after being affectionate.",
"The way you hide your face when I compliment you.",
"How your ears turn red when you’re embarrassed.",
"The way you laugh and lean forward like you can’t control it.",
"How your glasses fog up sometimes and you look confused.",
"The way you push your hair back when it annoys you.",
"How your highlights look brighter in sunlight.",
"The way your hair smells like your shampoo when you hug me.",
"How your hoodies always feel warmer than mine.",
"The way you look tiny inside oversized clothes.",
"How you steal my things and claim them as yours.",
"The way you say ‘mine’ jokingly but half mean it.",
"How you get dramatic about losing me in imaginary scenarios.",
"The way you overthink texts and ask what I meant.",
"How you reread conversations like they’re evidence.",
"The way you send screenshots just to confirm feelings.",
"How you say the dumbest cutest sounds like ‘WIWIIW.’",
"The way those sounds somehow mean ‘I love you.’",
"How you created a language only we understand.",
"The way you say ‘eepi sleepi’ like a spell to end the day.",
"How you make me want to sleep just to dream of you.",
"The way you sound calm when you’re sleepy.",
"How your sleepy voice is my favorite sound ever.",
"The way you refuse to sleep properly but still complain you’re tired.",
"How you blame me for keeping you awake but never hang up.",
"The way you stay even when you should rest.",
"How you choose me over comfort constantly.",
"The way you make sacrifices quietly.",
"How you never announce what you do for me.",
"The way you sit through my rants patiently.",
"How you listen even when I repeat myself.",
"The way you care about my smallest problems.",
"How you react like everything I say matters.",
"The way you celebrate my tiny wins.",
"How you hype me up when I doubt myself.",
"The way you see potential in me I don’t see.",
"How you make me kinder to myself.",
"The way you softened the angry parts of me.",
"How you healed things you never knew were broken.",
"The way loving you feels safe, not scary.",
"How you don’t judge my weird thoughts.",
"The way you accept every strange part of me.",
"How you match my energy no matter what mood I’m in.",
"The way you get extra chaotic when you’re happy.",
"How you send nonsense messages just to make me laugh.",
"The way you roast me and then cuddle me.",
"How you’re mean in the cutest way possible.",
"The way you bully me with love.",
"How you randomly bite me like it’s normal.",
"The way you hug too tight and refuse to let go.",
"How you pull my sleeve like a child crossing the road.",
"The way you act small and tough at the same time.",
"How you’re brave but still need reassurance.",
"The way you trust me enough to need me.",
"How you make me feel wanted every single day.",
"The way you say ‘come back’ when I tease you.",
"How you panic slightly when calls disconnect.",
"The way you immediately call again.",
"How you never let distance win.",
"The way you make a phone call feel like presence.",
"How even waiting in random shops felt special because you were there.",
"The way our first sushi date felt awkward and perfect.",
"How Phoenix South will always remind me of you.",
"The way that day quietly changed my life.",
"How every memory with you feels warmer than it should.",
"The way every future thought automatically includes you.",
"How loving you feels less like a choice and more like gravity.",
"The way I fall for you a little more every single day.",
"The way you say you’re not jealous and then ask twenty questions.",
"How you pretend not to care but absolutely do.",
"The way you get extra quiet when something bothers you.",
"How I can tell something’s wrong just from your tone.",
"The way you look down when you’re thinking too much.",
"How you overanalyze everything but still trust me.",
"The way you always come back to me after spiraling.",
"How you say ‘it’s okay’ when it clearly isn’t.",
"The way you let me fix it anyway.",
"How you cling harder when you’re scared.",
"The way you say ‘don’t leave’ without actually saying it.",
"How your sleepy voice sounds like it belongs next to me forever.",
"The way you mumble when you’re half conscious.",
"How you randomly wake up just to check if I’m still there.",
"The way you breathe slower when you calm down.",
"How you fall asleep mid-call but refuse to hang up.",
"The way you say my name softly when you need reassurance.",
"How you pout when I tease you too much.",
"The way you try to stay mad but end up laughing.",
"How your laugh starts quiet and then explodes.",
"The way you squint when you laugh too hard.",
"How your nose looks even cuter when you’re smiling.",
"The way your glasses reflect light when you look at me.",
"How your brown eyes look darker at night.",
"The way your highlights glow against dark backgrounds.",
"How your hair falls over your shoulders effortlessly.",
"The way you fix my hair like it’s your responsibility.",
"How you brush imaginary dust off me.",
"The way you adjust your glasses when you’re serious.",
"How you cross your arms when pretending to be mad.",
"The way you hug me tighter when you’re scared.",
"How you hold onto my sleeve like I might disappear.",
"The way you bite me randomly and then act innocent.",
"How you send ten texts in a row if I don’t reply.",
"The way you call again immediately after I hang up.",
"How you say ‘stay on call’ even when you’re exhausted.",
"The way you sacrifice sleep just to talk.",
"How you stayed awake all night once just for me.",
"The way you care more than you admit.",
"How you always check if I’ve eaten.",
"The way you scold me when I skip meals.",
"How you act like my personal alarm clock.",
"The way you randomly say ‘WA’ and expect a reaction.",
"How ‘WIWIIW’ somehow means something emotional.",
"The way we created our own tiny dictionary.",
"How ‘eepi sleepi’ feels like home.",
"The way shawarma tastes better because of you.",
"How tulips instantly make me think of your softness.",
"The way dark rooms feel less lonely when I imagine you there.",
"How you make silence feel full.",
"The way you match my mood without effort.",
"How you listen to my long explanations without complaining.",
"The way you ask questions because you care.",
"How you remember small details I forget.",
"The way you hype me up when I doubt myself.",
"How you calm me down when I overthink.",
"The way you make logic feel emotional and emotions feel logical.",
"How loving you feels balanced.",
"The way you make chaos feel comfortable.",
"How you turn awkward moments into something special.",
"The way you handled our first sushi date.",
"How Phoenix South doesn’t feel random anymore.",
"The way waiting around shops with you felt right.",
"How even the massage chair memory is cute now.",
"The way you get embarrassed but laugh anyway.",
"How you don’t pretend to be perfect.",
"The way you cry openly when something hurts.",
"How you let me see your real emotions.",
"The way you apologize too much.",
"How you forgive too quickly.",
"The way you need reassurance but still act strong.",
"How you say you’re fine but stay on call longer.",
"The way you panic when calls disconnect.",
"How you instantly call back.",
"The way you send voice notes when typing isn’t enough.",
"How you get dramatic about small things.",
"The way you threaten to hang up but never do.",
"How you tease me and then cling five seconds later.",
"The way you pretend you’re independent but still choose me constantly.",
"How you look smaller when you’re sad.",
"The way you hide your face in your hands.",
"How you peek through your fingers when embarrassed.",
"The way you look through your glasses when focused.",
"How your hair smells like your shampoo when you hug me.",
"The way you steal my hoodies and never give them back.",
"How my clothes look better on you.",
"The way you say ‘mine’ jokingly but mean it.",
"How you get protective without realizing.",
"The way you get possessive but cute about it.",
"How you always want to know where I am.",
"The way you make distance feel temporary.",
"How you make phone calls feel like presence.",
"The way you soften my harsh thoughts.",
"How you made me hate myself less.",
"The way you healed my mind quietly.",
"How loving you feels like gravity.",
"The way every future I imagine includes you traveling with me.",
"How marriage thoughts don’t scare me when it’s you.",
"The way kids jokes feel less like jokes.",
"How you make forever sound possible.",
"The way you’re chaos to the world and calm to me.",
"How you are both storm and shelter.",
"The way I choose you every single day.",
"How I would still choose you in every universe.",
"The way you say you’re not sleepy and then fall asleep two minutes later.",
"How you fight sleep like it personally offended you.",
"The way you get extra clingy when you’re tired.",
"How your voice turns softer at night.",
"The way you whisper instead of talk when you’re half asleep.",
"How you randomly say nonsense words and expect me to understand.",
"The way I actually do understand you somehow.",
"How you send ‘call me’ even when we just hung up.",
"The way you hate ending conversations.",
"How you stretch goodbyes into forever.",
"The way you say ‘okay bye’ five times before actually leaving.",
"How you miss me even five minutes after we talk.",
"The way you ask what I’m doing just to feel closer.",
"How you narrate your day like I’m there with you.",
"The way you overshare tiny details and I love every single one.",
"How you get jealous of imaginary girls in my head.",
"The way you pretend not to be jealous but interrogate me anyway.",
"How you say ‘who is she’ even when it’s obviously nothing.",
"The way you pout when I tease you about it.",
"How your jealousy feels like love instead of control.",
"The way you want me all to yourself.",
"How you look offended when I joke about leaving.",
"The way you hold me tighter after jokes like that.",
"How you silently stare when you’re overthinking.",
"The way your mind runs a thousand scenarios.",
"How you always come back to me at the end of every thought.",
"The way you say sorry for feeling too much.",
"How you feel everything so deeply.",
"The way you care more intensely than anyone I’ve ever known.",
"How your emotions are loud even when you’re quiet.",
"The way you cry when something small hurts you.",
"How you try to hide tears but fail.",
"The way you let me wipe them anyway.",
"How you trust me with your fragile moments.",
"The way you don’t pretend to be strong all the time.",
"How your honesty feels rare.",
"The way you’re chaotic with everyone but gentle with me.",
"How you soften your voice only for me.",
"The way you become calm when it’s just us.",
"How you look safer when you’re close to me.",
"The way you lean into me without thinking.",
"How your head fits perfectly against my shoulder.",
"The way you wrap your arms around me like you’re scared I’ll vanish.",
"How you squeeze tighter when I try to move away.",
"The way you say ‘wait’ when I stand up.",
"How you follow me around without realizing.",
"The way you steal my sleeve like it’s yours.",
"How you look tiny inside my hoodie.",
"The way my hoodie smells like your shampoo afterward.",
"How your shampoo smell feels more comforting than perfume.",
"The way you push your glasses up every few minutes.",
"How your glasses make you look serious and adorable at the same time.",
"The way you look over the top of them when you’re suspicious.",
"How your eyes look huge behind them sometimes.",
"The way your brown eyes glow in soft light.",
"How your highlights shine gold against dark rooms.",
"The way your hair falls perfectly messy.",
"How you tuck your hair behind your ear when nervous.",
"The way you fix my hair like it’s your job.",
"How you scold me for looking messy and then fix it yourself.",
"The way you act like my tiny wife already.",
"How you take care of me without realizing.",
"The way you remind me to sleep.",
"How you yell at me for skipping meals.",
"The way you act responsible but still chaotic.",
"How you send me random selfies and immediately regret it.",
"The way you delete messages and say ‘ignore that.’",
"How you get embarrassed over nothing.",
"The way you hide your face when I compliment you.",
"How you say ‘shut up’ but smile while saying it.",
"The way you pretend not to like praise but secretly love it.",
"How you bully me affectionately.",
"The way you roast me and then hug me.",
"How you bite me randomly like a tiny animal.",
"The way you say ‘don’t move’ while hugging.",
"How you complain about me but never leave.",
"The way you say I’m annoying and then call me five minutes later.",
"How you make fun of me and then defend me instantly.",
"The way you choose me every time.",
"How you stayed awake for me that one night even though you were exhausted.",
"The way you sacrifice sleep without complaining.",
"How you make calls feel like we’re in the same room.",
"The way distance feels fake when we talk.",
"How hours disappear when we’re together.",
"The way late nights feel peaceful with you.",
"How you make time feel softer.",
"The way you remember Phoenix South like it was yesterday.",
"How sushi tastes different because it reminds me of you.",
"The way even awkward first dates become precious memories.",
"How that day quietly changed my life forever.",
"The way waiting around shops with you felt like acceptance.",
"How you made ordinary places special just by being there.",
"The way you turn boring days into stories.",
"How you make me laugh at stupid things.",
"The way you say weird sounds like ‘WA’ and ‘WIWIIW.’",
"How those sounds mean more than actual words.",
"The way ‘eepi sleepi’ feels like a safe place.",
"How loving you feels both emotional and logical at the same time.",
"The way you calm my mind when it spirals.",
"How you made me less hateful toward myself.",
"The way you healed parts of me without trying.",
"How you make the future feel less scary.",
"The way I can imagine traveling the world with you.",
"How marriage thoughts don’t scare me when it’s you.",
"The way even kids jokes feel real with you.",
"How every version of my future automatically includes you.",
"The way you feel less like a chapter and more like the whole story.",
 "The way you pretend you’re not attached but panic when I take too long to reply.",
"How you always ask who I’m talking to even when you know the answer.",
"The way you look at me like I’m yours.",
"How you claim me without saying it directly.",
"The way you act jealous but then cuddle closer.",
"How you always want the last word before sleeping.",
"The way you say ‘don’t go’ in the softest voice.",
"How you make me feel needed without making me feel trapped.",
"The way you trust me enough to be clingy.",
"How your clinginess feels like comfort instead of pressure.",
"The way you send random ‘what are you doing’ texts just to talk.",
"How you get offended when I say I’m busy.",
"The way you want updates about everything.",
"How you narrate your day like I’m living it with you.",
"The way you say ‘listen’ before telling a long story.",
"How you exaggerate small things to make them dramatic.",
"The way you laugh at your own jokes.",
"How you say something chaotic and then act innocent.",
"The way you randomly go quiet and overthink.",
"How I can hear your mood change instantly.",
"The way you try to hide when you’re hurt.",
"How you soften the second I reassure you.",
"The way you say ‘okay’ in that tiny voice.",
"How you always forgive me faster than I deserve.",
"The way you apologize for being emotional.",
"How you feel everything deeply and unapologetically.",
"The way your emotions are intense but honest.",
"How you never fake your feelings.",
"The way you care more than anyone else would.",
"How you protect me even when you’re upset.",
"The way you hold on tighter when you’re scared.",
"How you squeeze my hand like I’m your anchor.",
"The way you rest your head on me when tired.",
"How you curl into me like you belong there.",
"The way your hoodie sleeves cover your hands.",
"How you hide inside my hoodie like it’s armor.",
"The way your shampoo scent lingers after hugs.",
"How you fix your glasses when nervous.",
"The way your glasses slide down your nose when focused.",
"How you squint at me suspiciously.",
"The way your brown eyes soften when you’re calm.",
"How your highlights glow against dark backgrounds.",
"The way you push your hair back dramatically.",
"How you look even cuter when you’re annoyed.",
"The way you scrunch your nose when laughing.",
"How you cover your mouth when embarrassed.",
"The way you hide behind your hands and peek through.",
"How you call me ‘Tanish’ in that specific tone.",
"The way you stretch my name when you want something.",
"How you say my name softly when you’re tired.",
"The way you mumble nonsense at night.",
"How you fight sleep and then instantly pass out.",
"The way you stay on call even when exhausted.",
"How you stayed awake once just because I needed you.",
"The way you sacrifice sleep like it’s nothing.",
"How you care about my meals more than your own.",
"The way you scold me for not resting.",
"How you act like you’re responsible but still chaotic.",
"The way you send ten texts before I answer one.",
"How you spam call like it’s an emergency.",
"The way you panic when the call disconnects.",
"How you immediately call back.",
"The way you never let distance win.",
"How you make calls feel like physical presence.",
"The way you say ‘WA’ like it explains everything.",
"How ‘WIWIIW’ somehow sounds emotional.",
"The way ‘eepi sleepi’ feels like our little world.",
"How shawarma instantly reminds me of you.",
"The way tulips feel softer because of you.",
"How dark rooms feel safe when I imagine you there.",
"The way our first sushi date still plays in my head.",
"How Phoenix South will never feel random again.",
"The way waiting in shops felt like a life shift.",
"How the massage chair memory still makes me laugh.",
"The way you looked embarrassed but kept laughing.",
"How you made awkward moments perfect.",
"The way you turned a simple date into something unforgettable.",
"How loving you feels like gravity pulling me back.",
"The way I fell first and never stopped falling.",
"How I say ‘I love you’ more but you show it louder.",
"The way you look at me like I’m your person.",
"How you make future thoughts feel calm.",
"The way I can imagine traveling with you everywhere.",
"How marriage thoughts don’t feel scary when it’s you.",
"The way kids jokes feel half serious.",
"How you make forever feel realistic instead of dramatic.",
"The way you softened my self-hate.",
"How you healed parts of my mind quietly.",
"The way you make me want to grow.",
"How you inspire me without trying.",
"The way you calm my overthinking logically.",
"How you balance emotion with reason.",
"The way you feel like both chaos and peace.",
"How you’re loud with the world but gentle with me.",
"The way you make me feel chosen.",
"How you make me feel wanted every single day.",
"The way every version of my future includes you.",
"How loving you feels less like effort and more like truth.",
"The way I would still choose you in every universe.",
"How even when you overthink, you still hold my hand.",
"The way you exist messy, chaotic, soft and somehow perfect for me."
];
